### ISSUE TITLE
Support Glip adapter for Hubot Conversations 

### ISSUE THREAD

**Issue by pkvenu** [tylerlong/hubot-glip#1]
The Glip adapter currently supports basic hubot commands like hear, send , reaply ...etc. but does not support a conversation. Can the adapter be enhances to support conversations using [hubot conversations](https://www.npmjs.com/package/hubot-conversation). 

A sample example can be found in https://github.com/pkvenu/zendesk

Running the example: 
zendesk > bin/hubot
zendesk zendesk list tickets

once this command finishes it will ask if you need more information ? yes or no?

> yes
> enter ticket number ? 5419
> It will output more details about the ticket.

**Comment by tylerlong** [comment]
@pkvenu 

[hubot conversations](https://www.npmjs.com/package/hubot-conversation) is an util library to help you build [hubot scripts](https://hubot.github.com/docs/#scripts), it depends on this [hubot adapter](https://hubot.github.com/docs/#adapters) project. For example, it also calls hear, send, reply...etc.

I won't add hubot conversations features to this repo because they belong to hubot scripts while this repo is about hubot adapter.

But I can help you to debug your issue.

**Comment by tylerlong** [comment]
I don't know what's wrong with [hubot conversasion](https://www.npmjs.com/package/hubot-conversation). I just couldn't get it work. Its implementation seems not very straightforward.

So I create my own implementation to support conversations:

```coffeescript
class Conversation
  constructor: ->
    @options = []
    @timer = null
  reset: -> # reset timer and options
    clearTimeout(@timer)
    @options = []
  startTimer: -> # clear the conversation after 30 seconds
    setTimeout((() -> @options = []), 30000)
  addOption: (regex, res, callback) -> # add an conversation option
    @options.push [regex, res, callback]
  execute: (content) -> # execute based on user input
    for option in @options
      [regex, res, callback] = option
      match = content.match regex
      if match != null # if matches the option
        callback(res, match)
        @reset()
        break

conversation = new Conversation()


module.exports = (robot) ->
  robot.hear /jump$/i, (res) ->
    res.send 'how many times?'
    conversation.reset() # reset existing conversation
    conversation.addOption(/^(\d+)$/, res, (res, match) ->
      for i in [0...match[1]]
        res.send 'jumps'
    )
    conversation.startTimer() # conversation expires in 30 seconds

  robot.hear /hungry$/i, (res) ->
    res.send 'What do you want to eat, bread or meat?'
    conversation.reset() # reset existing conversation
    conversation.addOption(/^bread$/i, res, (res, match) ->
      res.send 'Oh, I like bread too.'
    )
    conversation.addOption(/^meat$/i, res, (res, match) ->
      res.send "Oh, sorry meat has been sold out."
    )
    conversation.startTimer() # conversation expires in 30 seconds

  robot.hear /^([\s\S]+?)$/i, (res) ->
    conversation.execute res.match[1]
```

![image](https://cloud.githubusercontent.com/assets/733544/19470461/3e0cd1b4-9552-11e6-9268-3d6a69691b58.png)

**Comment by pkvenu** [comment]
@tylerlong : I think it should work. Thanks.
