### ISSUE TITLE
Details on how to integrate glip adapter

### ISSUE THREAD

**Issue by w601sxs** [tylerlong/hubot-glip#5]
Followed instructions in Readme.md and created my hubot; runs well locally. 

How do I integrate the src files (and all other files in your repo) into my hubot project? I  entered 'glip' (no quotes) when prompted for the adapter as instructed.

Thanks!

**Comment by tylerlong** [comment]
Here is a demo bot: https://github.com/tylerlong/glip-hubot-t

You can simply clone it and customize it.

**Comment by w601sxs** [comment]
Thanks! I followed instructions on glip-hubot-t, and this is what it returns:

PS C:\Users\Shreyas\myhubot-glip\glip-hubot-t> .\bin\hubot -a glip
npm WARN hubot-help@0.2.2 requires a peer of coffee-script@^1.12.6 but none was installed.
[Sun Dec 24 2017 22:07:14 GMT-0500 (Eastern Standard Time)] INFO Run
[Sun Dec 24 2017 22:07:14 GMT-0500 (Eastern Standard Time)] ERROR No saved token detected. You need to add the bot to Glip first.

What does "need to add the bot to Glip first" mean? I am running this on powershell in windows. Also, how do I add the environment variables? 

Thanks again!

**Comment by tylerlong** [comment]
Sorry for the late reply. Here is a video: https://www.youtube.com/watch?v=67yifrwUNsw&t=104s
